// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BarEcharts: typeof import('./src/components/page-echarts/src/BarEcharts.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    LineEchart: typeof import('./src/components/page-echarts/src/LineEchart.vue')['default']
    MapEcharts: typeof import('./src/components/page-echarts/src/MapEcharts.vue')['default']
    NavHeader: typeof import('./src/components/nav-header/src/NavHeader.vue')['default']
    NavMenu: typeof import('./src/components/nav-menu/src/NavMenu.vue')['default']
    PageContent: typeof import('./src/components/pageContent/src/pageContent.vue')['default']
    PageModal: typeof import('./src/components/pageModal/src/pageModal.vue')['default']
    PagePicChart: typeof import('./src/components/page-echarts/src/PagePicChart.vue')['default']
    PageSearch: typeof import('./src/components/pageSearch/src/pageSearch.vue')['default']
    PieEcharts: typeof import('./src/components/page-echarts/src/PieEcharts.vue')['default']
    RoseEcharts: typeof import('./src/components/page-echarts/src/RoseEcharts.vue')['default']
    UserInfo: typeof import('./src/components/nav-header/src/UserInfo.vue')['default']
  }
}

export { }
